AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/AsciiComments:
  Enabled: false
